# This workflow will install Python dependencies and run tests with a variety of Python versions

name: Python test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    environment: test Python versions

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest build twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWINE_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          make clean-dist
          python3 -m build
          twine upload --repository-url https://test.pypi.org/legacy/ --username __token__ --password $TWINE_TOKEN dist/*
          make test-install
